# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cccb7dc0b515dad938b584de1e5d5d353a11a247665d04dee0569040d7e7c5c88f3a86fbf8eb28be39c366c4fabf2f4a4e7ec55c494e851370799a4a9a3eb017

test:
  secret_key_base: 60c7cecc9e7bbba9bad89974a1d9b2951bbc046c97ee07d3617caac5fcc7e21e85028a76836ecb0961330af1c4d120c6a7d8e2b859b32c849f17deba3d92acfc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
